In [2]:
import numpy as np
arr2d_a = np.arange(25).reshape(5,5)
arr2d_b = np.arange(25,50).reshape(5,5)

In [3]:
print(arr2d_a)
print('----------------------------------')
print(arr2d_b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
----------------------------------
[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [5]:
vertical_joined_array = np.concatenate((arr2d_a,arr2d_b),axis=0)
vertical_joined_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [9]:
horizontal_joined_array = np.concatenate((arr2d_a,arr2d_b),axis=1)
horizontal_joined_array

array([[ 0,  1,  2,  3,  4, 25, 26, 27, 28, 29],
       [ 5,  6,  7,  8,  9, 30, 31, 32, 33, 34],
       [10, 11, 12, 13, 14, 35, 36, 37, 38, 39],
       [15, 16, 17, 18, 19, 40, 41, 42, 43, 44],
       [20, 21, 22, 23, 24, 45, 46, 47, 48, 49]])

In [12]:
arr1 = np.arange(20).reshape(4,5)
arr2 = np.arange(20,40).reshape(5,4)
print(arr1)
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [14]:
np.concatenate((arr1,arr2), axis=1)
# Shape / dimension should be same for concatenation

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 5

In [17]:
zero_element_array = np.zeros(6)
zero_element_array

array([0., 0., 0., 0., 0., 0.])

In [20]:
ones = np.ones(10).reshape(2,5)
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
zero2d = np.zeros((5,5))
zero2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
ones2d = np.ones((5,5))
ones2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
arr3d = np.ones((2,1,5))
arr3d

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

In [29]:
np.ones((5,3)) * 4

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [30]:
np.full((5,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [32]:
np.full((5,5),fill_value=10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [33]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [42]:
arr = np.arange(12).reshape(4,3)
arr.dtype
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
arre = arr[2,2] = 4.5
arre

4.5

In [45]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  4],
       [ 9, 10, 11]])

In [53]:
a = np.array([1,2,3,4,5,6]).reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
a.shape

(3, 2)

In [55]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
np.ones_like(a)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [65]:
np.random.randint(1,5, )

2

In [68]:
arr2d = np.random.randint(1,10,(5,5))
arr2d

array([[1, 2, 1, 1, 6],
       [6, 3, 7, 8, 7],
       [5, 4, 2, 4, 7],
       [7, 7, 8, 4, 4],
       [2, 4, 4, 6, 9]], dtype=int32)

In [80]:
!pip3 install pillow

   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/7.2 MB 570.5 kB/s eta 0:00:12
   -- ------------------------------------- 0.5/7.2 MB 570.5 kB/s eta 0:00:12
   -- ------------------------------------- 0.5/7.2 MB 570.5 kB/s eta 0:00:12
   ---- ----------------------------------- 0.8/7.2 MB 497.3 kB/s eta 0:00:1

In [81]:
from PIL import Image

# Pandas

## series
## data frame

# series

In [90]:
import pandas as pd

In [94]:
series = pd.Series([1,2,3,4,5,6])
fruits = pd.Series(['apple','banana','mango','grapes','kivi','fig'])
print(fruits)

0     apple
1    banana
2     mango
3    grapes
4      kivi
5       fig
dtype: object


In [95]:
fruits.shape

(6,)

In [96]:
fruits.index

RangeIndex(start=0, stop=6, step=1)

In [98]:
s1 = pd.Series([10,12,14,20,22,24])
s1

0    10
1    12
2    14
3    20
4    22
5    24
dtype: int64

In [99]:
print(type(s1))

<class 'pandas.core.series.Series'>


In [100]:
s1.size

6

In [101]:
s1.shape

(6,)

In [102]:
s1.index

RangeIndex(start=0, stop=6, step=1)

In [103]:
fruits.values

array(['apple', 'banana', 'mango', 'grapes', 'kivi', 'fig'], dtype=object)

In [104]:
s1.values

array([10, 12, 14, 20, 22, 24])

In [106]:
new_series = pd.Series([10,12,14,20,22,24], index=["Anday", "Burger", "Apples","Mangoes", "Alo", "Tomato"])

In [107]:
new_series

Anday      10
Burger     12
Apples     14
Mangoes    20
Alo        22
Tomato     24
dtype: int64

In [108]:
new_series.index=[9,8,7,9,0,2]

In [109]:
new_series

9    10
8    12
7    14
9    20
0    22
2    24
dtype: int64

In [113]:
print(f'After Using set_axis\n{series.set_axis(["Anday", "Burger", "Apples","Mangoes", "Alo",'ANY'])}')
print(f'Original series\n{series}')

After Using set_axis
Anday      1
Burger     2
Apples     3
Mangoes    4
Alo        5
ANY        6
dtype: int64
Original series
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [115]:
new_index = ['ali','kashan','Zulqarnain','sattar','babar','ahmad']
new_series = series.set_axis(new_index)

In [116]:
new_series

ali           1
kashan        2
Zulqarnain    3
sattar        4
babar         5
ahmad         6
dtype: int64

In [118]:
print(new_series['sattar'])
print(new_series['Zulqarnain'])

4
3


In [119]:
new_series['kashan':'Zulqarnain']

kashan        2
Zulqarnain    3
dtype: int64

In [120]:
s1

0    10
1    12
2    14
3    20
4    22
5    24
dtype: int64

In [123]:
s1 = pd.Series((10,12,14,20,22,24), index=["anday","burger","mangoes","kivi","sandwitch","a"])
s1

anday        10
burger       12
mangoes      14
kivi         20
sandwitch    22
a            24
dtype: int64

In [140]:
s1[::-1]

a            24
sandwitch    22
kivi         20
mangoes      14
burger       12
anday        10
dtype: int64

In [142]:
s1['anday':'burger']

anday     10
burger    12
dtype: int64

In [144]:
cities = ['karachi','lahore','quetta','pindi','sukher']
cities[3:6]

['pindi', 'sukher']

In [146]:
s1

anday        10
burger       12
mangoes      14
kivi         20
sandwitch    22
a            24
dtype: int64

In [145]:
s1.iloc[0:4]

anday      10
burger     12
mangoes    14
kivi       20
dtype: int64

In [150]:
print(s1['anday':'mangoes'])
print('----------------------------------------')
print(s1.loc['anday':'mangoes'])

anday      10
burger     12
mangoes    14
dtype: int64
----------------------------------------
anday      10
burger     12
mangoes    14
dtype: int64


In [151]:
print(s1.loc['mangoes'])
print(s1.iloc[2])

14
14


In [153]:
s1['anday'] = 'mery pasand ki value'
s1

anday        mery pasand ki value
burger                         12
mangoes                        14
kivi                           20
sandwitch                      22
a                              24
dtype: object

In [154]:
s1['anday']

'mery pasand ki value'

In [155]:
s1['mangoes']

14

In [156]:
s1[4]

C:\Users\Imran BT\AppData\Local\Temp\ipykernel_15580\3229368127.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[4]


22

In [157]:
s1[2:5]

mangoes      14
kivi         20
sandwitch    22
dtype: object

In [158]:
s1["anday":"sandwitch"]

anday        mery pasand ki value
burger                         12
mangoes                        14
kivi                           20
sandwitch                      22
dtype: object